// Generated by docs/research/sicau-colleges-2026-10-02/prepare-homepage-assets.py.
import emblem0 from "../assets/colleges/agriculture.webp?no-inline";
import emblem1 from "../assets/colleges/animal-science.webp?no-inline";
import emblem2 from "../assets/colleges/veterinary-medicine.webp?no-inline";
import emblem3 from "../assets/colleges/grassland-science.webp?no-inline";
import emblem4 from "../assets/colleges/fisheries.webp?no-inline";
import emblem5 from "../assets/colleges/forestry.webp?no-inline";
import emblem6 from "../assets/colleges/horticulture.webp?no-inline";
import emblem7 from "../assets/colleges/landscape-architecture.webp?no-inline";
import emblem8 from "../assets/colleges/resources.webp?no-inline";
import emblem9 from "../assets/colleges/environment.webp?no-inline";
import emblem10 from "../assets/colleges/economics.webp?no-inline";
import emblem11 from "../assets/colleges/management.webp?no-inline";
import emblem13 from "../assets/colleges/food-science.webp?no-inline";
import emblem14 from "../assets/colleges/science.webp?no-inline";
import emblem15 from "../assets/colleges/life-science.webp?no-inline";
import emblem16 from "../assets/colleges/mechanical-electrical.webp?no-inline";
import emblem17 from "../assets/colleges/information-engineering.webp?no-inline";
import emblem18 from "../assets/colleges/water-conservancy.webp?no-inline";
import emblem19 from "../assets/colleges/humanities.webp?no-inline";
import emblem20 from "../assets/colleges/public-administration.webp?no-inline";
import emblem21 from "../assets/colleges/law.webp?no-inline";
import emblem22 from "../assets/colleges/sports.webp?no-inline";
import emblem23 from "../assets/colleges/arts-media.webp?no-inline";
import emblem24 from "../assets/colleges/architecture-planning.webp?no-inline";
import emblem26 from "../assets/colleges/business-tourism.webp?no-inline";

export const colleges = [
  { id: "agriculture", name: "农学院", emblem: emblem0, whiteArtwork: false },
  {
    id: "animal-science",
    name: "动物科技学院",
    emblem: emblem1,
    whiteArtwork: false,
  },
  {
    id: "veterinary-medicine",
    name: "动物医学院",
    emblem: emblem2,
    whiteArtwork: false,
  },
  {
    id: "grassland-science",
    name: "草业科技学院",
    emblem: emblem3,
    whiteArtwork: false,
  },
  { id: "fisheries", name: "水产学院", emblem: emblem4, whiteArtwork: false },
  { id: "forestry", name: "林学院", emblem: emblem5, whiteArtwork: false },
  { id: "horticulture", name: "园艺学院", emblem: emblem6, whiteArtwork: true },
  {
    id: "landscape-architecture",
    name: "风景园林学院",
    emblem: emblem7,
    whiteArtwork: false,
  },
  { id: "resources", name: "资源学院", emblem: emblem8, whiteArtwork: false },
  { id: "environment", name: "环境学院", emblem: emblem9, whiteArtwork: false },
  { id: "economics", name: "经济学院", emblem: emblem10, whiteArtwork: false },
  { id: "management", name: "管理学院", emblem: emblem11, whiteArtwork: false },
  {
    id: "agricultural-engineering",
    name: "农业工程学院",
    emblem: null,
    whiteArtwork: false,
  },
  {
    id: "food-science",
    name: "食品学院",
    emblem: emblem13,
    whiteArtwork: true,
  },
  { id: "science", name: "理学院", emblem: emblem14, whiteArtwork: false },
  {
    id: "life-science",
    name: "生命科学学院",
    emblem: emblem15,
    whiteArtwork: false,
  },
  {
    id: "mechanical-electrical",
    name: "机电学院",
    emblem: emblem16,
    whiteArtwork: true,
  },
  {
    id: "information-engineering",
    name: "信息工程学院",
    emblem: emblem17,
    whiteArtwork: false,
  },
  {
    id: "water-conservancy",
    name: "水利水电学院",
    emblem: emblem18,
    whiteArtwork: false,
  },
  { id: "humanities", name: "人文学院", emblem: emblem19, whiteArtwork: false },
  {
    id: "public-administration",
    name: "公共管理学院",
    emblem: emblem20,
    whiteArtwork: false,
  },
  { id: "law", name: "法学院", emblem: emblem21, whiteArtwork: false },
  { id: "sports", name: "体育学院", emblem: emblem22, whiteArtwork: false },
  {
    id: "arts-media",
    name: "艺术与传媒学院",
    emblem: emblem23,
    whiteArtwork: false,
  },
  {
    id: "architecture-planning",
    name: "建筑与城乡规划学院",
    emblem: emblem24,
    whiteArtwork: true,
  },
  {
    id: "civil-engineering",
    name: "土木工程学院",
    emblem: null,
    whiteArtwork: false,
  },
  {
    id: "business-tourism",
    name: "商旅学院",
    emblem: emblem26,
    whiteArtwork: false,
  },
] as const;

export type CollegeId = (typeof colleges)[number]["id"];
